import pyautogui as py
py.press("win")
py.write("chrome")
py.sleep(1)
py.press("enter")
py.sleep(1)
py.write("whatsApp web")
py.sleep(1)
py.press("enter")
py.sleep(1)
# print(py.position())
py.click(x=256, y=502)
py.sleep(5)
# print(py.position())
py.click(x=274, y=304)
py.sleep(1)
py.write("mamis")
py.sleep(1)
# print(py.position())
py.click(x=302, y=573)
py.sleep(1)
py.write("Ola mamis, esta é uma mensagem automatizada pelo meu bot ")
py.sleep(1)
# print(py.position())
py.click(x=979, y=960)
py.sleep(1)
py.write("robo")
py.sleep(1)
# print(py.position())
py.click(x=611, y=485)
py.sleep(1)
# print(py.position())
py.click(x=980, y=948)
py.press("enter")